# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/order_status.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order/order_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18order/order_status.proto\x12\x05order*\x8f\x02\n\x0bOrderStatus\x12\x1a\n\x16ORDER_STATUS_UNDEFINED\x10\x00\x12\x19\n\x15ORDER_STATUS_ACCEPTED\x10\x01\x12\x19\n\x15ORDER_STATUS_REJECTED\x10\x02\x12\x18\n\x14ORDER_STATUS_PENDING\x10\x03\x12$\n ORDER_STATUS_PARTIALLY_COMPLETED\x10\x05\x12\x1a\n\x16ORDER_STATUS_COMPLETED\x10\x04\x12\x1a\n\x16ORDER_STATUS_CANCELLED\x10\x06\x12\x18\n\x14ORDER_STATUS_EXPIRED\x10\x07\x12\x1c\n\x18ORDER_STATUS_IN_PROGRESS\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order.order_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERSTATUS']._serialized_start=36
  _globals['_ORDERSTATUS']._serialized_end=307
# @@protoc_insertion_point(module_scope)
