# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/order.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order/order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from order import order_status_pb2 as order_dot_order__status__pb2
from order import order_type_pb2 as order_dot_order__type__pb2
from order import order_side_pb2 as order_dot_order__side__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order/order.proto\x12\x05order\x1a\x18order/order_status.proto\x1a\x16order/order_type.proto\x1a\x16order/order_side.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n\x0cOrderDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x30\n\x0c\x64\x61te_created\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rdate_executed\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x06status\x18\x05 \x01(\x0e\x32\x12.order.OrderStatus\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12\x0f\n\x07nominal\x18\x07 \x01(\t\x12\x15\n\rcash_quantity\x18\x08 \x01(\t\x12\r\n\x05price\x18\t \x01(\t\x12\x1e\n\x04type\x18\n \x01(\x0e\x32\x10.order.OrderType\x12\x1e\n\x04side\x18\x0b \x01(\x0e\x32\x10.order.OrderSide\"\x15\n\x07OrderID\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\tOrderList\x12#\n\x06orders\x18\x01 \x03(\x0b\x32\x13.order.OrderDetails2\xd6\x01\n\x05Order\x12\x37\n\x0b\x43reateOrder\x12\x13.order.OrderDetails\x1a\x13.order.OrderDetails\x12\x32\n\x0b\x44\x65leteOrder\x12\x0e.order.OrderID\x1a\x13.order.OrderDetails\x12/\n\x08GetOrder\x12\x0e.order.OrderID\x1a\x13.order.OrderDetails\x12/\n\x0cGetOrderList\x12\r.order.UserID\x1a\x10.order.OrderListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order.order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERDETAILS']._serialized_start=136
  _globals['_ORDERDETAILS']._serialized_end=453
  _globals['_ORDERID']._serialized_start=455
  _globals['_ORDERID']._serialized_end=476
  _globals['_USERID']._serialized_start=478
  _globals['_USERID']._serialized_end=498
  _globals['_ORDERLIST']._serialized_start=500
  _globals['_ORDERLIST']._serialized_end=548
  _globals['_ORDER']._serialized_start=551
  _globals['_ORDER']._serialized_end=765
# @@protoc_insertion_point(module_scope)
