name: Compile protobuf

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'version'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Compile protobuf
      shell: pwsh
      run: |
        ./build/New-ProtobufPackage.ps1 -Version "${{ github.event.inputs.name }}"

    - name: Check if there are any changes
      id: diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and Push Package
      if: steps.diff.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"
  
        git add .
        git commit -m "update Package"
        git push

    - name: Create Release
      shell: pwsh
      env:
        VERSION: ${{ github.event.inputs.name }}
      run: |
        $null = Invoke-RestMethod -Method Post -Headers @{
          "Accept"               = "application/vnd.github+json"
          "Authorization"        = "Bearer ${{ secrets.GITHUB_TOKEN }}"
          "X-GitHub-Api-Version" = "2022-11-28"
        } -Body $(
            @{
                "tag_name"               = "$($env:VERSION)"
                "name"                   = "$($env:VERSION) Release"
                "draft"                  = $false
                "prerelease"             = $false
                "generate_release_notes" = $false
            } | ConvertTo-Json
        ) -Uri "https://api.github.com/repos/${{ github.repository }}/releases"